### ISSUE TITLE
User Berechtigung beachten

### ISSUE THREAD

**Issue by marcohanke** [FriendsOfREDAXO/be_tools#10]
Im Multidomainumfeld bekommen User unterschiedliche Rechte für unterschiedliche Strukturzweige. in structure wird der Rest dann ausgeblendet, in be_tools ist er allerdings noch sichtbar was unschön ist.

**Comment by iceman-fx** [comment]
Wie kann ich das Verhalten nachbilden?
Wenn ich einem User nur die Rechte auf bestimmte Kategorien gebe, sehe ich in der Strukturverwaltung trotzdem alle anderen Kategorien.

**Comment by marcohanke** [comment]
Ich habe in der RootStruktur folgende Kategorien:
Domain A
- Seite 1
- Seite 2
...

Domain B
- Seite 1
- Seite 2
...

Benutzer A bekommt in der Benutzerrolle nur Zugriff auf die Domain A.
Benutzer B entsprechend nur auf Domain B.

Wenn ich mich als Benutzer A anmelde, lande ich in der Struktur direkt in Domain A und komme gar nicht auf die Hauptebene.

**Comment by iceman-fx** [comment]
ist umgesetzt
