### ISSUE TITLE
Strukturbaum verlangsamt das Backend

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/be_tools#12]
Der Strukturbaum sorgt für einen langsamen Seitenaufbau. Vor allem wenn viele Artikel geladen werden müssen. (Habe hier eine Kategorie mit über 2500 Artikeln) 

Lösungsansätze/Ideen: 
- Baum per Ajax laden (siehe Quicknavi) 
- Ab einer bestimmten Menge Unterartikel nicht listen, stattdessen Link in die Struktur anbieten.

**Comment by iceman-fx** [comment]
In der aktuellen Version wird der Baum per Ajax nachgeladen.
Damit wird hoffentlich die Performance in Deinem Fall verbessert.

**Comment by skerbis** [comment]
Yeeepeee 👍
