### ISSUE TITLE
Klassen und Funktionen vereinheitlichen

### ISSUE THREAD

**Issue by dergel** [FriendsOfREDAXO/be_tools#13]
Klassen in einzelne Dateien und in den lib Ordner
Funktionen zu passenden Methoden werden lassen
Die AddOn ID rausnehmen

**Comment by iceman-fx** [comment]
Was macht der lib-Ordner anders?
Die Bibliotheken sind ja eigentlich bereits in verschiedene Dateien aufgeteilt.
Ob nun Funktion oder Methode macht doch eigentlich keinen wirklichen Unterschied bei diesem Addon. 
Warum sollte die Addon ID raus?

**Comment by dergel** [comment]
Es wäre dann einheitlicher.
Es wäre dann klarer welche Klassen dann existieren, was sie machen wo sie zu finden sind. Das machen wir so bei vielen AddOns und soll eine Anregung sein. 
AddOn ID benutzen wir grundsätzlich nicht mehr, sondern eher dann noch die AddOnKeys selber

>Ob nun Funktion oder Methode macht doch eigentlich keinen wirklichen Unterschied bei diesem Addon.

Funktional nicht, aber von der Übersichtlichkeit her + die Klassen werden automatisch geladen.

**Comment by iceman-fx** [comment]
Dazu brauche ich dann wohl noch mehr Inputs.
Hast Du ein paar mehr Quellen, wo ich sehen/verstehen kannst, warum ihr z. B. keine Addon Keys mehr nutzt, etc?

**Comment by dergel** [comment]
schau dir mal die anderen AddOns an.. z.B. benutze ich bei Yform, weil es viele Klassen braucht, immer diesen prefix bei Klassen rex_yform_xxxxxx .. 
Wegen AddOn Struktur und was wohin gehört kannst du hier nachlesen: https://redaxo.org/doku/master/addon-struktur

Ansonsten einfach mal ein paar andere AddOns ansehen.
