### ISSUE TITLE
Aufgeklickte Pfade merken

### ISSUE THREAD

**Issue by dergel** [FriendsOfREDAXO/be_tools#14]
so, dass man diese nicht erneut neu aufklappen muss

**Comment by iceman-fx** [comment]
Hast Du schon in die Optionen geschaut?

**Comment by dergel** [comment]
Nein, habe ich komplett übersehen, sorry.. da ist es ja drin :) .. Leider klappt es bei mir nicht .. Chrome/Mac...

**Comment by dergel** [comment]
Ich sehe gerade .. er merkt sich einen geöffneten Ordner wenn ich wohl in einen Artikel klicke. Ich meinte aber aber auch die mehrere geöffneten Ordner. 

<img width="288" alt="Bildschirmfoto 2020-01-13 um 18 04 59" src="https://user-images.githubusercontent.com/322951/72275946-3c39b880-362f-11ea-9ae9-d668f92a55ae.png">

Bitte nicht falsch verstehen meine Issues. Ich versuche nur anzuregen ..

**Comment by iceman-fx** [comment]
Ich schaue mal im Script nach, ob man daran noch etwas as anpassen kann.

**Comment by iceman-fx** [comment]
Also ich kann das Verhalten bei mir nicht nachvollziehen (Chrome unter Windows).
Bei mir bleiben auch normal aufgeklickte Pfade (ohne den Artikel aufzurufen) offen, solange das Cookie dazu da ist.
