### ISSUE TITLE
be_tools umbenennen ?

### ISSUE THREAD

**Issue by dergel** [FriendsOfREDAXO/be_tools#16]
ich finde be_tools ist zu allgmein und sagt nichts richtiges aus .. Es könnte alles und nichts sein,
Fände es schon ok, wenn man sich hier auf den rextree konzentriert und vielleicht auch das AddOn entsprechend umbenennt ?

**Comment by tbaddade** [comment]
Wäre es nicht sinnvoll das AddOn in `structure_tweaks` einfließen zu lassen. Auch mit den Hintergedanken die AddOns übersichtlicher zu halten und insg. zu reduzieren

**Comment by iceman-fx** [comment]
@dergel 
Es ist ja mehr als nur rextree.
Auch werden sicher noch einige Tools dazukommen.

**Comment by iceman-fx** [comment]
@tbaddade 
Was macht structure tweaks? Habe es noch nie genutzt.

**Comment by tbaddade** [comment]
> Was macht structure tweaks? Habe es noch nie genutzt.

Siehe https://github.com/FriendsOfREDAXO/structure_tweaks

**Comment by iceman-fx** [comment]
> > Was macht structure tweaks? Habe es noch nie genutzt.
> 
> Siehe https://github.com/FriendsOfREDAXO/structure_tweaks

Wenn es richtig verstehe, werden damit nur ein paar Anpassungen an der Struktur Übersicht vorgenommen. 
Ist meines Erachtens ein anderer Ansatz, ein anderes Ziel.

**Comment by dergel** [comment]
Mir ging es bei dem Issue nur darum, dass es klarer wird, was sich dahinter verbirgt und ich bin eher Fan davon, wenn es eindeutiger ist. Bei Structure Tweak weiss ich es auch nicht konkret, aber zumindest schonmal an welcher Stelle es irgendwas erweitert :) .. Vielleicht überlegen was man an welcher Stelle zusammenfügen kann ?

**Comment by iceman-fx** [comment]
Da die einzelnen Funktionen verschiedene Bereiche tangieren, wie man es anders benennen können. Vorschläge sind gern willkommen 😀.
