### ISSUE TITLE
Design anpassen

### ISSUE THREAD

**Issue by dergel** [FriendsOfREDAXO/be_tools#17]
sieht, meines Erachtens, im Moment noch sehr eigensinnig aus. Würde Abstände, Farben etc anpassen.

**Comment by iceman-fx** [comment]
Was genau passt denn nicht?
M.M. nach passt es gut in den Originalskin von Rex5 rein.

**Comment by dergel** [comment]
Grundsätzlich finde ich es schon ganz cool. Mich stört am meisten die Headline mit dem Auf-/Zuklappicon und das die CustomerFarblinie nicht durchgängig ist. 
Irgendwie passen die 3 Bereich im Headerbereich im Moment, meines Erachtens, noch nicht so gut zusammen.

Den Baum selber finde ich gut. 

<img width="798" alt="Bildschirmfoto 2020-01-13 um 18 07 19" src="https://user-images.githubusercontent.com/322951/72276371-0b0db800-3630-11ea-8827-e234b1dd1ff0.png">

**Comment by iceman-fx** [comment]
Zur Customer Linie kann ich aktuell nicht viel sagen.
Da dies wiederum ein separates Addon ist, könnte es daran selbst liegen. 

Hättest Du bzgl. Der Headline einen Vorschlag?

**Comment by tbaddade** [comment]
> Zur Customer Linie kann ich aktuell nicht viel sagen.
Da dies wiederum ein separates Addon ist, könnte es daran selbst liegen.

Du musst deinen Part ein wenig herunter schieben.

**Comment by iceman-fx** [comment]
Dann passt es nicht mehr im Originalskin. 
Ohne es jetzt angeschaut zu haben, wird die Customer Linie wohl nicht an den Header gelegt, sondern verschiebt die nav und content Bereiche.

**Comment by iceman-fx** [comment]
Moin.
ich habe soeben mal in mein Addon geschaut.
Die Einbindung ist analog der Nav und des Contentbereiches als table-cell.
Alle 3 Spalten liegen auf einer Ebene. Mit "runterschieben" ist da nicht viel.

Die customerlinie selbst muss daher vermutlich eine fehlerhafte Einbindung haben.
Welches Addon erzeugt denn diese Linie?

**Comment by iceman-fx** [comment]
Hab das Addon gefunden: customizer Plugin vom be_style-Addon.

Und wie ich schon vermutet habe, liegt der Fehler wo anders.
Für die header-Leiste hat einer im CSS vergessen, einen z-index anzugeben, da diese Leiste als Position absolute deklariert wurde.

**Comment by tbaddade** [comment]
Mit kleinen Anpassungen kann man das im be_tools AddOn auch erreichen.

Siehe Screens
<img width="937" alt="Bildschirmfoto 2020-01-14 um 09 30 28" src="https://user-images.githubusercontent.com/338267/72327029-962e9280-36b0-11ea-8da3-4592ae615d8d.png">


<img width="1194" alt="Bildschirmfoto 2020-01-14 um 09 32 04" src="https://user-images.githubusercontent.com/338267/72327109-be1df600-36b0-11ea-83f1-d531f609f617.png">

**Comment by iceman-fx** [comment]
Sicher kann man dies.
Aber wenn es woanders falsch ist, sollte es dort behoben werden, da sonst das Problem an anderer Stelle weiterhin bestehen bleiben kann.

PS: Meine Anpassungen mache ich immer für den Originalskin.

**Comment by tbaddade** [comment]
Kannst du zeigen was du jetzt angepasst hast?

Hinweis: Wenn du committest kannst du via `#17` auf das Issue verweisen. Im Issue bekommt man dann einen Link zum Commit angezeigt, was das Verfolgen sehr erleichtert.

**Comment by iceman-fx** [comment]
Ich habe nix angepasst.

PS: keine Ahnung was Du mit commitest #17 so richtig meinst. 
Ich nutze github nicht da ich es selbst nicht brauche und kenne mich damit auch nicht wirklich aus. 
Die Addons stelle ich hier nur ein, weil es einige wünschen und man dort einfacher Wünsche und Fehler melden kann.
