### ISSUE TITLE
Homepagelink wird nicht eingebunden

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/be_tools#2]
Konflikt mit anderem AddOn?

**Comment by iceman-fx** [comment]
Hast Du ein anderes Theme installiert?
Welche Addons laufen denn bei dir?

**Comment by skerbis** [comment]
Customizer vielleicht?

**Comment by iceman-fx** [comment]
Customizer gerade getestet.
Alles i.O.

**Comment by iceman-fx** [comment]
Hast du hierzu noch weitere Infos bzgl. Deiner Redaxo Umgebung?

**Comment by skerbis** [comment]
Ich finde nicht den Auslöser. Ich mache es erstmal zu hier. Wenn sonst keiner das Problem hat.
