### ISSUE TITLE
Notices vermeiden

### ISSUE THREAD

**Issue by tito-tema** [FriendsOfREDAXO/be_tools#20]
Ich bekomme jede Menge Notices wegen undeklarierter Variablen. 

Folgendes hilft: in der Datei **functions_be.inc.php**
`//Variablen deklarieren
    $mypage = "be_tools";
    $cnt = "";`  

 ersetzen durch

`//Variablen deklarieren
	$mypage = "be_tools";
	$cnt = "";
	$search = $replace = [];`

**Comment by iceman-fx** [comment]
Was für notices erhältst du denn?

**Comment by tito-tema** [comment]
Hi Falko,
System / Logdateien:

Notice | Undefined variable: replace | redaxo/src/addons/be_tools/functions/functions_be.inc.php | Zeile 47
und
Notice | Undefined variable: search  | redaxo/src/addons/be_tools/functions/functions_be.inc.php | Zeile 47

Gruß
Tito
