### ISSUE TITLE
Beachtung der Structure Tweaks Einschränkungen

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/be_tools#22]
Es wäre toll, wenn das rex_tree die Einschränkungen im Structure tweaks AddOn beachten würde. 
z.B. Ausblendung von Kategorien und Startartikel.

**Comment by iceman-fx** [comment]
Welche Einschränkungen ?

**Comment by iceman-fx** [comment]
Hat denn das ST Addon entsprechende ExtensionPoints?

**Comment by skerbis** [comment]
Man kann Kategorien oder Startartikel verstecken. z.B. für Hilfsartikel die durch Redakteure nicht gepflegt werden sollen. 
Ich glaube das AddOn nutzt eher die Extension points vom structure AddOn.
