### ISSUE TITLE
Sidebar festpinnen verschwunden?

### ISSUE THREAD

**Issue by rkemmere** [FriendsOfREDAXO/be_tools#23]
Hallo Falko,

kann es sein, dass beim letzten Release das "Sidebar Pin" weggefallen ist? 
Das fand ich eigentlich immer hilfreich und super das es jeder User selber einstellen konnte.

**Comment by iceman-fx** [comment]
Ähmm, nö.

Ist alles beim aktuellen Release noch da,
Auch nach Update auf Rex5.12 wird es bei mir in mehreren Installation korrekt angezeit.

Schießt evtl. ein JS bei Dir quer?

**Comment by rkemmere** [comment]
Hmm, komisch jetzt wird es angezeigt. Also kann geschlossen werden. Alles top ;)
