### ISSUE TITLE
Strukturbaum sollte ausgeblendet werden wenn User keine Rechte für Artikel und Kategorien hat. 

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/be_tools#24]

**Comment by iceman-fx** [comment]
Was hat das Recht für das structure_addon mit dem Strukturbaum zu tun?
Wenn der Admin die Einstellungen im Addon vornimmt, warum soll dann der gesamte Baum raus, wenn nur einige wenige Kategorien verstellt werden?

PS: Wäre es nicht einfacher, wenn dies gleich vom structure_addon durchgeführt wird?

**Comment by skerbis** [comment]
rex_tree wird angezeigt obwohl der User keine Rechte auf Kategorien in der Struktur hat. Das meine ich. 
<img width="792" alt="Bildschirmfoto 2021-03-30 um 13 19 34" src="https://user-images.githubusercontent.com/791247/112980779-97839800-915a-11eb-991b-0fe29f013b4c.png">

**Comment by iceman-fx** [comment]
Achso, nicht das structure tweaks addon ist gemeint, sondern die normalen Kategorierechte.

**Comment by skerbis** [comment]
Ja. Kamst n bisschen durcheinander wg. meinem vorherigen Issue? 😅

**Comment by iceman-fx** [comment]
Ja. Und zu viele Struktur Addons 😁

**Comment by abra100pro** [comment]
Viele Add-ons zur Struktur zeigen (mir), dass es da offenbar Bedarf gibt.

**Comment by iceman-fx** [comment]
@abra100pro Ja, da gebe ich Dir recht. Wenn dies alle "ab Werk" schon drin wäre, wäre es toll.

**Comment by iceman-fx** [comment]
@skerbis Kannst Du mir mal schnell auf die Sprünge helfen, wie ich die einzelnen Rechte der Rolle prüfen kann?

**Comment by skerbis** [comment]
@iceman-fx sorry I'm late: 
`rex::getUser()->hasPerm('structure/hasStructurePerm'));`
true oder false

**Comment by iceman-fx** [comment]
@skerbis 
Dies klappt leider nicht: rex::getUser()->hasPerm('structure/hasStructurePerm'));

Da erhalte ich immer false, egal ob das "Alle Kategorien"-Recht gesetzt ist oder nicht.
