### ISSUE TITLE
Ausbau in Redaxo

### ISSUE THREAD

**Issue by abra100pro** [FriendsOfREDAXO/be_tools#25]
Das Add-on ist genau das, was mir seit Anbeginn in Redaxo gefehlt hat. Die aktuelle Struktur hat grosses Potenzial zur Verbesserung. Du/Ihr hebt das auf ein neues Level - schön wäre eine richtige Integration in Redaxo (R6?) Ich habe da gleich einen Feature request daraus gemacht:

https://github.com/redaxo/redaxo/issues/4658

All the best,
Alex

**Comment by iceman-fx** [comment]
Hi Alex,
das Addon gab es auch schon in der R4.

Aber ich stimme Dir zu, auch ich würde es nativ im Redaxo besser finden, da damit die Verzahnung besser umsetzbar wäre.

**Comment by iceman-fx** [comment]
Was die Funktionen des Rechtsklickmenüs angeht, so ist dies die Adaption aus der R4.
Man müsste schauen, ob man dies auch mit Ajax hinbekommt und wie man dann nur den Contentbereich per Ajax refreshen kann, um diese Änderungen dort auch parallel anzeigen zu lassen.

Drag & Drop ist im Javascript des Trees bereits vorgesehen, aber von mir nicht für Redaxo genutzt.
