### ISSUE TITLE
Farben?

### ISSUE THREAD

**Issue by abra100pro** [FriendsOfREDAXO/be_tools#26]
Was bedeuten die Farben Rot, Blau, Grün, Orangegelb der Icons?

Mein Vorschlag wäre:
Rot: offline
Grün: online (selbe Farbe wie der Text "offline" in der bisherigen Strukturansicht)

Cool wären diese weitere, die aber mit anderen Funktionen zu tun haben:

Orange: offline (Farbe müsste dann auch im Rex core geändert werden)
Rot: gesperrt (müsste auch in den Core - kommt zur Zeit nur mit dem Add-on "access-denied".
Blau: geändert, aber nicht veröffentlicht (kommt ja mit dem Sub-add-on "version" als Funktion dazu: Arbeits-/Life-Version)

**Comment by abra100pro** [comment]
Vielleicht ist weniger auch mehr?:

<img width="227" alt="image" src="https://user-images.githubusercontent.com/7532646/116781284-36652200-aa82-11eb-8b45-b23da4bff44f.png">

**Comment by iceman-fx** [comment]
Da kann ich Dir nicht ganz folgen.
Orangegelb gibt es nicht, es sei denn, irgendein anderes Addon ändert die Farben.

Aktuell ist es so:
Rot = offline
Blau = Standard (online)
Grün = Startartikel

Hier der Screenshot der Originalfarben:

![Unbenannt-1](https://user-images.githubusercontent.com/4291047/116782698-f5254000-aa8a-11eb-9845-ce860b0a4ea7.jpg)

**Comment by abra100pro** [comment]
Ah, das Grün sieht bei mir mehr nach Ocker (oder eben Orange) aus. 

Eine kleine, effektive Anpassung wäre, die Originalfarbe von Redaxo zu übernehmen: Grün anstatt Blau für online.

**Comment by iceman-fx** [comment]
Ich habe es bei mir mal testweise auf grün anstatt blau umgestellt.
Irgendwie passt dies nicht nun nicht mehr ins Bild.

![ScreenHunter 233](https://user-images.githubusercontent.com/4291047/118361507-165a5600-b58c-11eb-8490-b8e9de665dd7.png)

Ich würde es nicht grün machen.

**Comment by iceman-fx** [comment]
Ich habe es jetzt an Rex 5.12 angelehnt, wobei aktive Artikel blau sind.
