### ISSUE TITLE
Structure Tree defekt, wenn in Rollen mehrere Mountpoints definiert. 

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/be_tools#28]
- Bus & Bahn und Service sind Unterkategorien einer Hauptkategorie 
- YoungTicket und SchokoTicket sind Hauptkategorien. 

Irgendwie kommt das Tree dabei durcheinander. 

<img width="852" alt="Bildschirmfoto 2021-05-05 um 17 25 26" src="https://user-images.githubusercontent.com/791247/117166842-0772e700-adc7-11eb-9b52-e6fb3e487fae.png">

Gerne DM in Slack, ich zeige es Dir gerne live.

**Comment by iceman-fx** [comment]
Was meinst Du mit "in Rollen mehrere Mountpoints definiert" ?
Wie kann ich dass bei mir nachstellen, um es testen und ggf. beheben zu können?

**Comment by skerbis** [comment]
In den Rollen bei Kategorien, Kategorien in verschieden Ebenen auswählen. 

z.B. 
- Unternehmen
-- Bus & Bahn *
-- Irgendwas
-- Service*
- Andere Kategorie
- Noch eine
- YoungTicket*
- SchokoTicket*

Die mit * sind ausgewählt. 
Gerne zeige ich es Dir auch live.

**Comment by iceman-fx** [comment]
@skerbis
Hierbei benötige ich Hilfe, da ich es nicht hinbekomme, die Struktur sauber erstellen zu lassen.
Problem ist, dass ich die gesamte Struktur als ul li benötige - für alle Ebenen, was aber nicht funktioniert, wenn ich in einer tieferen Struktur beginne und später noch eine Root-Kategorie kommt.

Hast Du eine Idee?

https://github.com/iceman-fx/be_tools/blob/8ce8f886bcfc128afbccd40f1e5950ee49a93826/functions/functions_be_tree.inc.php#L336
