### ISSUE TITLE
Nicht alle Module in der Auswahl, wenn aktiviert

### ISSUE THREAD

**Issue by abra100pro** [FriendsOfREDAXO/be_tools#29]
Ein ganz komisches Phänomen, welches ein Kunde von mir hatt, ich konnte es nichtmal nachvollziehen, obwohl wir beide Mac/Safari nutzen:

bei Ihm:
![image](https://user-images.githubusercontent.com/7532646/119018222-2adb8b80-b99c-11eb-9f0f-7e056da73ff6.png)

bei mir:
<img width="670" alt="image" src="https://user-images.githubusercontent.com/7532646/119018358-48a8f080-b99c-11eb-8e47-8c9d98355d47.png">

be-tools deaktiviert: Fehler bei Kunde weg. Wird wohl sehr schwer herauszufinden sein....

**Comment by iceman-fx** [comment]
Kann ich bei mir nicht nachvollziehen, zumal das Addon mit den Modulen nichts macht bzw. zu tun hat.
Kommt denn irgendein JS Fehler?

**Comment by iceman-fx** [comment]
Schau mal genau hin bei dem Beispiel von Deinem Kunden.
Ganz oben siehst Du noch 1 Pixel vom Namen des Moduls.
Es scheint eher, als ib die Klappbox bei seinem Browser nicht jn den Screen passt.

**Comment by iceman-fx** [comment]
Was mir auch auffällt ist, dass die Blockauswahl bei Deinem Kunden nach oben statt nach unten aufgeht.
Und dort liegt dann die Header-Leiste von Redaxo darüber.

**Comment by iceman-fx** [comment]
Ich konnte es jetzt nachstellen und mit v1.6.1 lösen.
Das Problem lag in der neuen Sidebar-Minimierung, wo ich ein overflow:hidden drin hatte.

**Comment by abra100pro** [comment]
Top! Danke für die schnelle Lösung.
