### ISSUE TITLE
Button für Navigation

### ISSUE THREAD

**Issue by pschuchmann** [FriendsOfREDAXO/be_tools#3]
Hey,

ich hab eben testweise mal das be_tools installiert und behalte es direkt ;) 

Eine Sache ist uns aufgefallen, bzw. wäre vielleicht wünschenswert. Und zwar haben die meisten Apps die Möglichkeit bei eingeblendeter App noch einen Button zu klicken, der das Menü aufgeklappt lässt.

Weiter ist mir aufgefallen, dass der Text vom Addon Watson nicht ausgeblendet wird. Dort wird ein svg als Icon verwendet, hatte per Zufall gesehen, dass es da bereits mal einen Fix für den CKE5 gab. Vielleicht hilft er dort auch.

**Comment by iceman-fx** [comment]
Also einen Fixierenbutton, welcher die Ein-/Ausklappautomatik deaktiviert?

Das mit dem Watson Icon schaue ich mir. 
Es wäre da einfacher, wenn die Addons nur die Std. Icons nutzen würden.

**Comment by skerbis** [comment]
Es gibt keine Standard Icons - es kann ein beliebiges Bild eingesetzt werden. Das ist so in der Package vorgesehen. Viele bedienen sich der rex-icons oder Font awsome Symbole weil‘s so bequem ist

**Comment by pschuchmann** [comment]
Genau so etwas in die Richtung @iceman-fx  ;)

Und wie @skerbis schreibt, da hat jeder Addon Entwickler recht freie Hand. Segen und Fluch zugleich ;)

**Comment by iceman-fx** [comment]
Auch hier noch einmal die Frage zum Fixierbutton:

Lieber den Fixierbutton umsetzen oder eine Userbezogene Auswahl (https://github.com/FriendsOfREDAXO/be_tools/issues/8) wie bei der Quicknavigation?
Beides macht keinen Sinn.

**Comment by pschuchmann** [comment]
Hey,

wenn ich das richtig verstanden habe, soll es auch bei @skerbis um einen Fixierbutton gehen. Thomas meinte, glaube ich zumindest, dass es schön wäre den Default der Anzeige des Menüs pro User festlegen zu können. Also als admin standardmäßig aufgeklappt und als Redakteur standardmäßig minimiert beispielsweise. Korrigiere mich @skerbis, wenn ich falsch liege.

**Comment by skerbis** [comment]
Mein Vorschlag ist, dass der Redakteur selbst entscheiden kann welche Funktion und Darstellung er/sie wünscht

**Comment by iceman-fx** [comment]
Fixierbutton ist integriert

**Comment by pschuchmann** [comment]
Habs eben direkt installiert, ich finds top! Danke dir!
