### ISSUE TITLE
Kontextmenu Look

### ISSUE THREAD

**Issue by abra100pro** [FriendsOfREDAXO/be_tools#30]
Ich habe mittels CSS das Kontextmenu etwas verändert - vielleicht gefällt's dir ja so auch besser - siehe Screenshots.

![bet-css](https://user-images.githubusercontent.com/7532646/120447633-14193980-c38b-11eb-85c6-13fbfa46fc26.png)

![bet-wirkung](https://user-images.githubusercontent.com/7532646/120447646-167b9380-c38b-11eb-8148-e1bfcb8d4452.png)

**Comment by iceman-fx** [comment]
background: #FFF;
    border: 1px solid #d2d2d2;
    box-shadow: 1px 1px 10px rgb(0 0 0 / 30%);
    border-radius: 4px;

**Comment by abra100pro** [comment]
Ich weiss nicht genau, was Du damit meinst. Diese Werte stehen ja in meinem Screenshot - übersehe ich etwas?
Danke für dein Feedback dazu.

**Comment by iceman-fx** [comment]
Das ist nur der code den ich einbauen werde. Als Ablage.

**Comment by iceman-fx** [comment]
Wurde in der Version 1.7 mit umgesetzt.
Danke nochmal.
