### ISSUE TITLE
Farbschema bei automatischem Rex-Dark-Theme wird mobile ignoriert

### ISSUE THREAD

**Issue by danspringer** [FriendsOfREDAXO/be_tools#31]
Wenn man am Smartphone ist und in Redaxo das Backend-Theme "Automatisch" aktiviert hat, wird die Treestructure farblich nicht korrekt dargestellt.
Wenn man das Backend-Theme manuell auf Dunkel stellt, ist alles korrekt.

Backend-Theme "Automatisch"
![Bildschirmfoto 2022-04-15 um 14 53 40](https://user-images.githubusercontent.com/16903055/163573373-570fed14-147d-409f-a6f7-ecbe5bd1c60e.png)

Backend-Theme "Dunkel"
![Bildschirmfoto 2022-04-15 um 14 52 38](https://user-images.githubusercontent.com/16903055/163573414-d1de1aa6-ed5c-4d0d-9d9d-4a110baa6305.png)

<details>
<summary>System report (REDAXO 5.13.2, PHP 8.0.17, MariaDB 10.2.43)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.13.2     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 8.0.17     |
|       OPcache | yes        |
|        Xdebug | yes        |

| Database      |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.2.43 |
| Character set | utf8mb4         |

| Server        |              |
| ------------: | :----------- |
|            OS | Linux        |
|          SAPI | fpm-fcgi     |
|     Webserver | nginx/1.20.1 |

| Request       |                      |
| ------------: | :------------------- |
|       Browser | Chrome/100.0.4896.88 |
|      Protocol | HTTP/2.0             |
|         HTTPS | yes                  |

| Packages                   |            |
| -------------------------: | :--------- |
|                   be_tools | 1.7.3      |

</details>

**Comment by iceman-fx** [comment]
Ok, ist korrigiert.
