### ISSUE TITLE
Deprecation issue

### ISSUE THREAD

**Issue by AndiLeni** [FriendsOfREDAXO/be_tools#32]
Hallo,

ich bekomme unter php 8.1 eine Deprecation Warnung:

`Deprecated: preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in redaxo\src\addons\be_tools\pages\index.php on line 20`

**Comment by iceman-fx** [comment]
In der neuen Version sollte dies gefixt sein.
