### ISSUE TITLE
Struckturbaum läd nicht wenn Sprach-Prio geändert

### ISSUE THREAD

**Issue by tito-tema** [FriendsOfREDAXO/be_tools#33]
Hi Falko,
ich habe folgendes Phänomen festgestellt: 
Ursprünlich waren zwei Sprachen für eine Seite konfiguriert. (de id=1/prio=1 und en id=2/prio=2). Auf de wurde dann verzichtet, also Sprache offline gesetellt. Beim Redaxo-Login landet mal aber auf der de-Seite, also habe ich alle Artikel offline gestellt, damit man sieht, dass man die Sprache wechseln muss. 
Dann dachte ich, ich kann ja die Prios der Sprachen ändern, um vielleicht beim Redaxo-Login direkt auf der EN-Seite zu landen. Funktioniert auch. Aber der Struckturbaum lädt nicht und verursacht ein permanentes Neuladen der Seite. Schade eigentlich ;-)

**Comment by iceman-fx** [comment]
Hi.
Wie kann ich das Ganze nachstellen?
Habe es ehrlich nicht ganz verstanden, wann dieses Problem Auftritt.

**Comment by tito-tema** [comment]
Tach auch, 
nimm eine Redaxo-Installation mit 2 Sprachen. Die Sprache mit der id=1 sollte auch prio=1 haben.
Setzte die Sprache mit der id=1 unter System offline und schalte danach alle Artikel dieser Sprache offline.
Beim Redaxo-Login landest du dann auf Sprache 1, aber alle Artikel sind rot/offline.
Dann unter System die Prio der Sprache 2 von 2 auf 1 ändern und dann auf Struktur zurück gehen … und fertig ist der Reloader 😉
Auch Cache löschen und logout/login schafft keine Abhilfe.
Gruß Tito

**Comment by tema-web** [comment]
Hi Falko,

Nimm eine Redaxo-Installation mit 2 Sprachen. Die Sprache mit der id=1 sollte auch prio=1 haben.
Setzte die Sprache mit der id=1 unter System offline und schalte danach alle Artikel dieser Sprache offline.
Beim Redaxo-Login landest du dann auf Sprache 1, aber alle Artikel sind rot/offline.
Dann unter System die Prio der Sprache 2 von 2 auf 1 ändern und dann auf Struktur zurück gehen … und fertig ist der Reloader 😉
Auch Cache löschen und logout/login schafft keine Abhilfe

Mit freundlichen Grüßen / Best regards
Andreas Tietz

TEMA Technologie Marketing AG
Communications to Success

Aachener-und-Münchener-Allee 9
52074 Aachen
Germany
Tel.: +49 241 88970-351<tel:+4924188970351>
Fax: +49 241 88970-999<tel:+4924188970999>
Email: ***@***.******@***.***>
www.tema.de<http://www.tema.de/>


Aachen   Berlin   Dortmund   Stuttgart   Beijing   Chicago   Paris
--------------------------------------------------------------------------------------------------------------------
Vorstand: Dr. Günter Bleimann-Gather, Hans Symanczik
Vorsitzender des Aufsichtsrates: Prof. Dr. Malte Gather
Amtsgericht Aachen, HRB 8320



Von: Falko Müller ***@***.***>
Datum: Donnerstag, 1. Dezember 2022 um 15:39
An: iceman-fx/be_tools ***@***.***>
Cc: Andreas Tietz ***@***.***>, Author ***@***.***>
Betreff: Re: [iceman-fx/be_tools] Struckturbaum läd nicht wenn Sprach-Prio geändert (Issue #33)

Hi.
Wie kann ich das Ganze nachstellen?
Habe es ehrlich nicht ganz verstanden, wann dieses Problem Auftritt.

**Comment by iceman-fx** [comment]
Hi Andreas,
in der neuen 1.7.7 ist dies nun gefixt.

**Comment by tito-tema** [comment]
cool 😊
