### ISSUE TITLE
BE Tools & REX AddOn Nav ausblenden 

### ISSUE THREAD

**Issue by madiko** [FriendsOfREDAXO/be_tools#38]
Moin zusammen. Ich würde gern BE Tools zusammen mit dem REX BE-Tweak "[AddOn Nav ausblenden](https://friendsofredaxo.github.io/tricks/backend/backend_snippets#navhide)" (FOR Tricks) nutzen. 

Die mögen sich nicht gleichzeitig. Was nicht funzt, ist der Link auf das Icon und damit das Toggle um zu den AddOns zu gelangen. Das heißt, ich deaktiviere momentan immer das AddOn BE Tools, wenn ich auf ein anderes AddOn zugreifen möchte. Das geht, ist jedoch nicht effektiv.

Gern beteilige ich mich an der Lösung. Mir ist jedoch nicht ersichtlich, wo es genau hakt. Hat eine:r von Euch dazu eine Lösung oder eine Idee, wo ich ansetzen muss? Danke.

**Comment by iceman-fx** [comment]
Gehe ich recht in der Annahme, dass dieses Verhalten nur entsteht, wenn Du die Hauptnavi über be_tools minimieren lässt?

**Comment by iceman-fx** [comment]
Ich deaktiviere bei den Titels die Events (Klicks).
Daher greift der Klick auf das Icon nicht mehr.

**Comment by madiko** [comment]
Danke für die Rückmeldung.

> Gehe ich recht in der Annahme, dass dieses Verhalten nur entsteht, wenn Du die Hauptnavi über be_tools minimieren lässt?

Ja. (Das ist der Haupt-Grund für mich, das AddOn BE Tools zu nutzen.)

> Ich deaktiviere bei den Titels die Events (Klicks).
> Daher greift der Klick auf das Icon nicht mehr.

Welche Überlegungen stehen bitte dahinter? 
Ließe sich eine Lösung finden?
Oder brauche ich doch einen eigenen Ansatz für meinen Wunsch, die Nav zu minimieren?

**Comment by madiko** [comment]
Notiz: Neue Zwischen-Lösung ist, dass ich den FOR-Trick deaktiviert habe. 
Das ist sinnvoller als das AddOn BE Tools zu aktivieren/deaktivieren.

**Comment by iceman-fx** [comment]
Ich arbeite bereits an einer Integration des FOR Tricks in das be-tools addon

**Comment by iceman-fx** [comment]
So, die neue Version ist online.
Damit sollte nun das gewünschte Verhalten direkt im be_tools hergestellt werden können.

**Comment by madiko** [comment]
Hallo, 
Danke für die super schnelle Lösung und neue Version.
Leider funktioniert sie bei mir nicht. 

Vielleicht jedoch auch ganz gut? Denn wenn die AddOns eingeklappt sind und es funtzt nicht, kommt man nicht wieder an die Einstellungen. Das heißt, das AddOn müsste unter die Haupt-AddOns (da man es ja nicht mehr erreichte). Macht das für Dich Sinn?

Oder funkt doch noch was anderes bei mir rein?
(Trick ist weiter auskommentiert. Das kann ich also schon ausschließen.)

![grafik](https://github.com/user-attachments/assets/4d1ce33e-101a-453f-a725-d4f06709dfcc)

**Comment by iceman-fx** [comment]
Ich habe das jetzt auch mehreren anderen Installationen bei mir geprüft.
Klappt problemlos.

Hast Du mal den Cache des Browser komplett geleert?
Evtl. greift da eines der CSS noch nicht.
