### ISSUE TITLE
Warum werden die Assets immer neu geladen?

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/be_tools#6]
https://github.com/FriendsOfREDAXO/be_tools/blob/d4d3e9c8e01f9a5d71d0a1340bbeee5f599cda74/boot.php#L54

Evtl. auch interessant: https://redaxo.org/doku/master/addon-assets#javascripte

**Comment by iceman-fx** [comment]
Wenn man dies nicht macht, werden nach einem Update die JS/CSS-Dateien nicht sofort geladen, so dass Änderungen diesen Dateien nicht erscheinen.
Fast jedes Addon macht dies so. Schau mal in den Quellcode vom Backend.

**Comment by skerbis** [comment]
@iceman-fx dafür ist doch der interne buster da. Aktuell werden die assets hier bei jedem request neu geladen. Siehe Doku und meinen PR. 😎
Welches Addon macht es denn so wie dieses? Ich kann keins finden?

**Comment by iceman-fx** [comment]
Ich habe da in deinem PR auf die schnelle nicht viel gefunden.
Redaxo macht dies also selbstständig?

**Comment by skerbis** [comment]
😀ja
