### ISSUE TITLE
Wunsch:: Per User Settings

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/be_tools#8]
Hallo und Danke für das tolle AddOn. Es kommt leider unterschiedlich bei meinen Redakteuren an. Einige finden es super und modern andere möchten lieber ihr gewohntes Menü haben. 
Daher wäre es sinnvoll, denke ich, die Ansichtseinstellungen per User durchzuführen. Als Beispiel hierfür kannst Du dich an die Favoritenverwaltung der QuickNavigaten halten. 

https://github.com/FriendsOfREDAXO/quick_navigation/blob/d3037c7d0ed111d2fa1da630059babd31b6c8706/pages/config.php#L11-L13

BEISPIEL: 
https://github.com/FriendsOfREDAXO/quick_navigation/blob/d3037c7d0ed111d2fa1da630059babd31b6c8706/pages/config.php#L36

**Comment by iceman-fx** [comment]
Hi Skerbis,
diese Funktionalität ist interessant, auch wenn man diese nicht wirklich in der Quicknavigation war nimmt.

Um nicht alles doppelt zu programmieren sollte man jetzt abstimmen, ob man lieber einen Fixierbutton (https://github.com/FriendsOfREDAXO/be_tools/issues/3) oder diese Einstellvariante umsetzen sollte.
Beides macht keinen Sinn.

**Comment by skerbis** [comment]
Was Dir lieber ist

**Comment by iceman-fx** [comment]
Ich mach hier erst einmal zu, da eine alternative Funktionalität nun vorhanden ist.
