### ISSUE TITLE
Inhaber ist nicht FriendsOfRedaxo

### ISSUE THREAD

**Issue by marcohanke** [FriendsOfREDAXO/be_tools#9]
Im Installer weißt noch nichts auf FOR hin sondern alles auf Falko.
@iceman-fx jemand vom Core kann dir den AddonKey ersetzen

**Comment by iceman-fx** [comment]
@dergel 
Kannst du mir hierzu etwas sagen, es erklären, was da zu machen wäre?

**Comment by dergel** [comment]
Weiss ich leider auch nicht .. in der LICENSE steht MIT und Friendsofredaxo .. Vielleicht in der README das noch mit reinschreiben ? 
@marcohanke An welchen Stellen meinst du ?

**Comment by marcohanke** [comment]
Im Installer steht Falko Müller als Autor. Soweit ich weiß, muss jemand über FOR einen AddonKey erstellen damit das Addon auch von FOR ausgeliefert wird. Sorry für die ungenaue Beschreibung.

**Comment by bloep** [comment]
@dergel du müsstest in der redaxo.org Datenbank den AddonKey von Falkos MyRedaxo Account auf FORs Account übertragen. You know 😉 😘  (alternativ auch @gharlan )

**Comment by dergel** [comment]
ist geändert.

**Comment by iceman-fx** [comment]
Frage:
Hat die Änderung bei Euch etwas damit zu tun, dass mein Addon jetzt nicht mehr im Installer unter "Eigene hochladen" zu finden ist?

Wie lade ich denn jetzt ein Update hoch, damit es im Installer erscheint?

**Comment by gharlan** [comment]
Du musst dich im Installer nun mit `friendsofredaxo` und dem zugehörigen Api-Key einloggen.
Sende ihn dir in Slack.
